GET http://{{host}}/users/posts/rating
Authorization: Bearer {{token}}
Accept: application/json
###

GET http://{{host}}/users/posts/rating?page=2
Authorization: Bearer {{token}}
Accept: application/json
###
